library(shiny)
library(shinydashboard)
library(d3heatmap)

decadeList <- c("1950s", "1960s", "1970s", "1980s", "1990s", "2000s")

units_g <- readRDS("units.RDS")
value_g <- readRDS("value.RDS")

dashboardPage(
  dashboardHeader(title = "Music Data"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Home",
               tabName = "home", 
               icon = icon("home")),
      menuItem("US Music Sales: 1973-2019",
               tabName = "income",
               icon = icon("dollar")),
      menuItem("Genre Similarity: 1950s-2000s",
               tabName = "genre",
               icon = icon("music")),
      menuItem("References",
               tabName = "references",
               icon = icon("book"))
      
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "home",
        fluidRow(
          box(
            title = "Welcome to Music Data!", 
            "The field of music has changed vastly over the years.", 
            "This includes the way people listen to music, as the platform in which people listen music to changed from vinyls and CDs to streaming services like Spotify or Apple Music.", 
            "In our \"Income\" tab, we are visualizing this change by tracking how musicians earn income.",
            "In our \"Genre\" tab, we are visualizing the change in musical elements like timbre and loudness between genres from the 1950s to 2000s"
          ),
          box(
            img(
              src = "music2.jpg"
            )
          )
        )
      ),
      tabItem(tabName = "income",
        fluidRow(
          box(
            title = "United States Recorded Music Sales Volumes and Revenue by Format",
            background = "light-blue",
            "The formats (CD, Vinyl, Downloaded Albums, Streaming Services, etc.) that
            people use to listen to music have evolved over the years. We aimed to
            visualize this evolution by using datasets from the RIAA that show the 
            number of units in millions of each format and the revenue in millions
            of USD generated by each format from 1973 to 2019."
          ),
          box(
            title = "How to Use This Page",
            background = "yellow",
            "Click the 'Units' tab to view the music sales volume by format in millions of units",
            "Click the 'Revenue' tab to view the music sales volume by format in millions of dollars, and click the 'Value adjusted for inflation' to view the revenue adjusted for inflation",
            "For both tabs, click 'Select Unit Format' or 'Select Revenue Format' to choose which formats of music income sources to display.",
            "You can use the 'Select years to display' sliding bars to select which years to visualize.",
            "After displaying your plot, drag over a section of the plot to output the actual values of the section you chose in a table beneath the plot."
          )
        ),
        fluidRow(
          sidebarPanel(
            sliderInput(inputId = "year_slider",
                        label = "Select years to display:",
                        min = 1973,
                        max = 2019,
                        value = c(1973, 2019)
            )
          ),
          mainPanel(
            tabsetPanel(type = "tabs",
                        tabPanel("Units", 
                                 selectInput(
                                   inputId = "unit_type",
                                   label = "Select Unit Format:",
                                   choices = unique(units_g$unit_type),
                                   multiple = TRUE),
                                 plotOutput("unitPlot",
                                             brush = "plot_brush"),
                                 verbatimTextOutput("info_brush")
                                 ),
                        tabPanel("Revenue",  
                                 selectInput(
                                   inputId = "value_type",
                                   label = "Select Revenue Format:",
                                   choices = unique(value_g[["yes_inf"]]$value_type),
                                   multiple = TRUE
                                 ),
                                 radioButtons("inf", "choose adjusted for inflation or not:",
                                              c("Value not adjusted for inflation" = "not_inf",
                                                "Value adjusted for inflation" = "yes_inf")
                                 ),
                                 plotOutput("valuePlot",
                                            brush = "plot_brush"),
                                 verbatimTextOutput("value_brush")
                        )
            #plotOutput("incomePlot",
            #click = "plot_click"),
            #verbatimTextOutput("info_click")
            )
          )
        )
      ),
      tabItem(tabName = "genre",
        fluidRow(
          box(
            title = "Changes in Genre Similarity by Decade: 1950s-2000s",
            background = "light-blue",
            "The similarity between different musical genres has been changing
             throughout the past several decades. We aimed to visualize these changes
             using a dataset that shows how many songs per decade (1950s-2000s) were
             cross-tagged as two different genres. We visualized these changes on an 
             interactive heatmap using hierarchical clustering via a dendrogram to
             calculate a Pearson correlation coefficient (between -1 and 1)."
          ),
          box(
            title = "Pearson Correlation Coefficient",
            background = "yellow",
            "High Value = High Correlation Between Genres", tags$br(),
            "Low Value = Low Correlation Between Genres", tags$br(), tags$br(),
            "Value = 1: Total Positive Linear Correlation", tags$br(),
            "Value = 0: No Linear Correlation", tags$br(),
            "Value = -1: Total Negative Linear Correlation"
          )
        ),
        fluidRow(
          sidebarPanel(
            selectInput(
              inputId = "decade",
              label = "Select decade:",
              choices = decadeList
            )
          ),
          mainPanel(
            d3heatmapOutput("heatmapPlot")
          )
        )
      ),
      tabItem(tabName = "references",
         fluidRow(
            box(
              title = "US Music Sales Data",
              "Bass, M. (2020). U.S. Sales Database. RIAA. Retrieved November 18,
              2020, from ",
              a("RIAA", href = "https://www.riaa.com/u-s-sales-database/")
              )
         ),
         fluidRow(
            box(
              title = "Genre Similarity Data",
              solidHeader = TRUE,
              "Mani, S. (2017). C3shouvikmani/Million-Song-Dataset-Visualization.
              GitHub. Retrieved November 18, 2020, from ",
              a("Github", href = "https://github.com/c3shouvikmani/Million-Song-Dataset-Visualization")
          )
        )
      )
    )
  )
)



